### ISSUE TITLE
メッセージ一覧チェック

### ISSUE THREAD

**Issue by fujita0830** [internousdevwork/cyan#28]
メッセージ一覧(機能設計書p.5)通りのメッセージになっているか各自
確認

- [x]  澤根
- [x]  藤澤
- [x]  永浦
- [x]  近藤
- [x]  加藤
- [x]  藤田
- [x]  渡邉
- [x]  高橋

**Comment by sakurakosawane** [comment]
澤根チェックしました～！

**Comment by ryuichi-kondo** [comment]
近藤チェックしました

**Comment by kato1111** [comment]
加藤チェックしました

**Comment by takaryo8** [comment]
高橋チェックしました

**Comment by mayu-watanabe** [comment]
渡邉チェックしました
