### ISSUE TITLE
mCategoryDTOListの余分な記述削除

### ISSUE THREAD

**Issue by fujita0830** [internousdevwork/cyan#30]
`private List<MCategoryDTO> mCategoryDTOList = new ArrayList<MCategoryDTO>();`
上記記述削除
getterとsetterも削除

- [x] DeleteCartAction
- [x]  GoLoginAction
- [x]  MyPageAction
- [x] ProductDetailsAction
- [x]  ProductListAction
- [x]  PurchaseHistoryAction
- [x]  SearchItemAction

**Comment by sakurakosawane** [comment]
* MyPageAction
* PurchaseHistoryAction
の修正完了　澤根

**Comment by ryuichi-kondo** [comment]
DeleteCartAction修正完了　近藤

**Comment by mayu-watanabe** [comment]
ProductDetailsAction
 ProductListAction
完了　渡邉
