### ISSUE TITLE
商品購入履歴

### ISSUE THREAD

**Issue by fujita0830** [internousdevwork/cyan#42]
- [x] 項目の表示順は設計書の順番に合わせる
- [x] 購入履歴テーブルに登録される宛先情報が、決済時に選択した宛先ではなく、宛先情報選択画面の一番上に表示される情報になっているので修正。

**Comment by sakurakosawane** [comment]
上段の、項目の順番は完了しました。
下段今、検証中です。澤根

**Comment by fujita0830** [comment]
`SettlementCompleteAction`
38行目あたりかも？
