### ISSUE TITLE
placeholderの使用を統一

### ISSUE THREAD

**Issue by fujita0830** [internousdevwork/cyan#43]
使用するに統一

- [x]  澤根
- [x]  藤澤
- [x]  永浦
- [x]  近藤
- [x]  加藤
- [x]  藤田
- [x]  渡邉
- [x]  高橋

**Comment by mayu-watanabe** [comment]
担当機能に入力欄の使用箇所無し　渡邉

**Comment by kato1111** [comment]
確認済み　加藤

**Comment by ryuichi-kondo** [comment]
担当機能に使用箇所なし　近藤

**Comment by fujita0830** [comment]
- 使用箇所 :header.jsp使用確認　藤田

**Comment by sakurakosawane** [comment]
担当機能該当なし　澤根

**Comment by nk19930907** [comment]
該当なし　かい

**Comment by takaryo8** [comment]
createDestination.jspを修正しました　高橋
