### ISSUE TITLE
未ログイン時にも「宛先情報入力画面」飛ぶことができる

### ISSUE THREAD

**Issue by kf-haru** [internousdevwork/cyan#5]
ログインしてなくても、ログインしている時しか見れない画面「宛先情報入力画面」に飛ぶことができる

ログインする時にID保存にチェックしてからログアウトして、未ログイン状態で
カートから決済画面に進むと、ログイン画面に飛ばず
ログインしている時しか見れない画面「宛先情報入力画面」に飛ぶことができる

LogoutAction？CreateDestinationAction？

**Comment by mayu-watanabe** [comment]
推測･･･
SettlementConfirmActionの39行目
if(session.containsKey("loginId")) {　で、
・ログインしている状態で保持しているloginId
・未ログインで保持しているloginId
が同じとして認識されている？ログイン判定が必要？？

**Comment by mayu-watanabe** [comment]
```
		if(savedLoginId==true) {
			session.put("savedLoginId", true);
			session.put("loginId", loginId);
		} else {
			session.put("savedLoginId", false);
			session.remove("logined", loginId);
		}`
```

LoginAction　41行目のlogined　→　loginId

**Comment by fujita0830** [comment]
> ログインしてなくても、ログインしている時しか見れない画面「宛先情報入力画面」に飛ぶことができる

宛先情報入力画面→`createDestination.jsp`

`CreateDestinationAction`の判定がエラーで出るはずが、
サクセスで出てしまっている。

**Comment by fujita0830** [comment]
`SettlementConfirmAction`でログイン判定をなぜか
`if(!session.containsKey("loginId"))`行っていた。
ログイン判定は`if(session.get("logined").equals(0))`で行う
