### ISSUE TITLE
connection.close();をtrycatchで囲むのかを統一

### ISSUE THREAD

**Issue by fujita0830** [internousdevwork/cyan#52]
try catchで囲む

- [x]  澤根
- [x]  藤澤
- [x]  永浦
- [x]  近藤
- [x]  加藤
- [x]  藤田
- [x]  渡邉
- [x]  高橋

**Comment by mayu-watanabe** [comment]
DestinationInfoDAOの2個目のメソッドのみ囲まれていない様子。

**Comment by fujita0830** [comment]
あとで念のため確認　保留
