### ISSUE TITLE
各Actionでのresultの指定をプログラム対応表と合わせる※プログラム対応表にない返り値を記述しない

### ISSUE THREAD

**Issue by fujita0830** [internousdevwork/cyan#54]
SettlementCompleteActionで設計書と、プログラム対応表が違う？

- [x]  澤根
- [x]  藤澤
- [x]  永浦
- [x]  近藤
- [x]  加藤
- [x]  藤田
- [x]  渡邉
- [x]  高橋

**Comment by mayu-watanabe** [comment]
- ProductListAction
- ProductDetailsAction
対応してます　渡邉

**Comment by takaryo8** [comment]
・SettlementConfirmAction
・CreateDestinationAction
・CreateDestinationConfirmAction
・CreateDestinationCompleteAction
異常ありません。　高橋

**Comment by ryuichi-kondo** [comment]
・AddCartAction
・CartAction
・DeleteCartAction
対応してます　近藤

**Comment by kf-haru** [comment]
例えばstruts.xmlに「ERROR」の遷移先が指定されていないActionクラスで、
String result = ERROR;
と書かれているのって、意味ないよね、というお話だそうです

**Comment by nk19930907** [comment]
修正ずみ

**Comment by sakurakosawane** [comment]
修正しました　澤根

**Comment by kf-haru** [comment]
担当箇所では該当なし　けいこ

**Comment by kato1111** [comment]
修正しました　加藤

**Comment by takaryo8** [comment]
修正しました　高橋

**Comment by ryuichi-kondo** [comment]
修正しました　近藤

**Comment by fujita0830** [comment]
確認済み
