### ISSUE TITLE
登録日、更新日の仕様変更について(sqlファイル、一部dao)

### ISSUE THREAD

**Issue by ryuichi-kondo** [internousdevwork/cyan#60]
- DestinationInfoDAO[ 22行目のinsert文：update_dateのvaluesを‘0000-01-01’からnow()に変更] 

- PurchaseHistoryInfoDAO[ 104行目のinsert文：update_dateのvaluesを‘0000-01-01’からnow()に変更]

**Comment by ryuichi-kondo** [comment]
cyan.sqlは確認して、修正点ありませんでした。

**Comment by sakurakosawane** [comment]
PurchaseHistoryInfoDAO、nowに修正しました

**Comment by takaryo8** [comment]
DestinationInfoDAO　修正しました　高橋
