### ISSUE TITLE
テキストボックスの色が変わる時と変わらないときがあるので統一

### ISSUE THREAD

**Issue by fujita0830** [internousdevwork/cyan#76]

**Comment by mayu-watanabe** [comment]
現在login.jspの入力欄のtextfieldでクラス名　class="txt-yellow"　が設定されており、userCreate.jspとresetPassword.jspではクラス未設定のため、ログイン画面でのみテキストボックスの色が変わるようになっている。どっちに統一する？

`<s:textfield name="loginId" class="txt-yellow" placeholder="ユーザーID" autocomplete="off" /></td>`

**Comment by kf-haru** [comment]
変える必要はないとのことなので変えずに終了
