### ISSUE TITLE
カート内で同じ商品が重複して表示される

### ISSUE THREAD

**Issue by kf-haru** [internousdevwork/cyan#8]
ログインしている時と未ログイン状態で同じ商品をカートに入れると合算されない
（ログイン状態でカート追加した和菓子1と未ログイン状態でカート追加した和菓子1がどちらもカート内にある）
その後同じ商品を追加するとどちらとも入れた数だけ増えてしまう
（もともと【和菓子1　1個、和菓子1　1個】が【和菓子1　2個、和菓子1　2個】になる）

・未ログイン時にカートに商品を追加し、その後にログインしてから同じ商品をカートに追加すると数が増えるのではなく、別の商品として別れて表示されてしまう。
また、その後に、同じ商品をカートに追加すると、追加した分、別れた商品の数がそれぞれ増えてしまう。
ex.未ログイン時にAという商品を１つカートを追加
　カートの中身：A １個・・・想定通り
→その後にログイン
　カートの中身：A １個・・・想定通り
→ログイン後にAという商品を１つカートを追加
　カートの中身：A １個・・・想定しているカートの中身：A ２個
　　　　　　　　A １個
→その後に、Aという商品を２つカートを追加
　カートの中身：A ３個・・・想定しているカートの中身：A ４個
　　　　　　　　A ３個

**Comment by mayu-watanabe** [comment]
未ログイン時
和菓子１　1個追加
和菓子2　2個追加
カートには、
和菓子１　1個
和菓子2　2個

ログイン
和菓子1　1個追加

カートに、
和菓子１　2個
和菓子１　3個
和菓子２　1個
和菓子２　1個

と表示されてる

**Comment by ryuichi-kondo** [comment]
session.removeを使う？

**Comment by kf-haru** [comment]
LoginActionのloginedとloginIdを修正したことが関係ありそうかと思ったけど同様のエラーが出た

**Comment by fujita0830** [comment]
ｓｑｌ見比べるもしくは、
セッション関連のなんかしらかも？

**Comment by fujita0830** [comment]
同じ商品IDなのに、別のものとして認識されてしまうのが問題点？

**Comment by fujita0830** [comment]
カートアクションで、同じ商品IDのものを足して表示する処理をすれば解決するが、
それだと、MAMPPの使用上、うまくいかないことがありそうなため、
講師の方が対処法を考えてくれそうなため、保留。
